// SIDEBAR - TYPES
export const OPEN_SIDEBAR = 'SIDEBAR_OPEN'

// TOPBAR - TYPES
export const OPEN_NAVBAR_IN_TOPBAR = 'OPEN_NAVBAR_IN_TOPBAR'
export const CHANGE_THEME = 'CHANGE_THEME'

// CHARTS - TYPES

// pie BR
export const FETCH_CHART_PIE_BR_REQUEST = 'FETCH_CHART_PIE_BR_REQUEST'
export const FETCH_CHART_PIE_BR_SUCCESS = 'FETCH_CHART_PIE_BR_SUCCESS'
export const FETCH_CHART_PIE_BR_FAILURE = 'FETCH_CHART_PIE_BR_FAILURE'
// pie USA
export const FETCH_CHART_PIE_USA_REQUEST = 'FETCH_CHART_PIE_USA_REQUEST'
export const FETCH_CHART_PIE_USA_SUCCESS = 'FETCH_CHART_PIE_USA_SUCCESS'
export const FETCH_CHART_PIE_USA_FAILURE = 'FETCH_CHART_PIE_USA_FAILURE'

// line
export const FETCH_CHART_LINE_REQUEST = 'FETCH_CHART_LINE_REQUEST'
export const FETCH_CHART_LINE_SUCCESS = 'FETCH_CHART_LINE_SUCCESS'
export const FETCH_CHART_LINE_FAILURE = 'FETCH_CHART_LINE_FAILURE'

// choropleth
export const FETCH_CHART_CHOROPLETH_REQUEST = 'FETCH_CHART_CHOROPLETH_REQUEST'
export const FETCH_CHART_CHOROPLETH_SUCCESS = 'FETCH_CHART_CHOROPLETH_SUCCESS'
export const FETCH_CHART_CHOROPLETH_FAILURE = 'FETCH_CHART_CHOROPLETH_FAILURE'

// bar
export const FETCH_CHART_BAR_REQUEST = 'FETCH_CHART_BAR_REQUEST'
export const FETCH_CHART_BAR_SUCCESS = 'FETCH_CHART_BAR_SUCCESS'
export const FETCH_CHART_BAR_FAILURE = 'FETCH_CHART_BAR_FAILURE'

// bullet
export const FETCH_CHART_BULLET_REQUEST = 'FETCH_CHART_BULLET_REQUEST'
export const FETCH_CHART_BULLET_SUCCESS = 'FETCH_CHART_BULLET_SUCCESS'
export const FETCH_CHART_BULLET_FAILURE = 'FETCH_CHART_BULLET_FAILURE'
