// SIDEBAR - TYPES
export const OPEN_SIDEBAR = 'SIDEBAR_OPEN'

// TOPBAR - TYPES
export const OPEN_NAVBAR_IN_TOPBAR = 'OPEN_NAVBAR_IN_TOPBAR'
export const CHANGE_THEME = 'CHANGE_THEME'

// CHARTS - TYPES
export const FETCH_CHART_BAR = 'FETCH_CHART_BAR'
